### PR TITLE
Fix database upgrade issue when OpenNMS is upgraded and a few other small improvements

### PR DESCRIPTION
**Pull request by deejgregor**

### CODE REVIEW

**Review by agalue — APPROVED** [review]
It looks great; I liked your approach for handling the conditional triggering of the database regardless if the chart is upgrading from a previous version.

I'll try to find some time today to test it, but that should not prevent merging.

Here is what I'd like to try:
* Deploy H30 with the latest chart. Clean installation without previous content on PVCs.
* Deploy the old Helm Chart with H29 and then upgrade to H30 based on this PR.
* Deploy H30 with the latest chart and then upgrade to H31-snapshot.
* Deploy the old Helm Chart with H29 and then upgrade to H31-snapshot based on this PR.

By "latest chart", I mean using this branch (or after it is merged).

**Comment by deejgregor** [comment]
> * Deploy the old Helm Chart with H29 and then upgrade to H31-snapshot based on this PR.

I tested all of these except this one. I didn’t do a jump straight from 29 with the old chart to 31, but I will do that one shortly unless you’ve already started testing.

**Comment by agalue** [comment]
> > * Deploy the old Helm Chart with H29 and then upgrade to H31-snapshot based on this PR.
> 
> I tested all of these except this one. I didn’t do a jump straight from 29 with the old chart to 31, but I will do that one shortly unless you’ve already started testing.

I haven't started yet; go for it. I'm glad you tested all the other cases.

**Comment by deejgregor** [comment]
Completed testing of this, and it was fine, so ready to merge:
> Deploy the old Helm Chart with H29 and then upgrade to H31-snapshot based on this PR.

**Pull request merged**
